### ISSUE TITLE
Why not SASS?

### ISSUE THREAD

**Issue by dlewand691** [f-prime/Blunt#4]
This is a great idea, I've struggled with this a lot myself. Building this with SASS would save a lot of time, add a lot of flexibility/customization, make maintenance easier, and combine a ton of repeatable elements. Just saying...

**Comment by rattanakchea** [comment]
I agree. It seems every value is hard-coded which makes it hard to modify in the future.

I have a question, is Blunt mobile first or desktop first CSS framework, or neither one ? It seems we have to specify {{size}} for either small, medium, large screens.

**Comment by loup-brun** [comment]
+1 for SASS sources.

**Comment by f-prime** [comment]
Blunt was obviously not written by hand. It's generated from some Python scripts that I didn't really consider releasing. I haven't ever really used SASS for anything serious, so it didn't cross my mind to write the first version in it. Though it seems like it would make maintenance much easier. Normally I don't like these kinds of questions, but in this case you're probably right. I'll see about redoing this in SASS. @rattanakchea I made it mobile first. You don't always have to specify, but I have found it to be easier in a lot of different situations. Creating a one size fits all solution almost never works. Having the ability to easily choose which rules get applied to which screen sizes works better for me.

**Comment by loup-brun** [comment]
@dlewand691 Here's a similar utility-first library written in SASS (therefore customizable): [GOSP-SASS](https://github.com/gosp-project/gosp-sass) ([docs](https://gosp-sass.com/docs/get-started.html)).

**Comment by f-prime** [comment]
I just finished the initial rewrite of Blunt using SCSS. There is probably a bit of cleaning up that can be done... but it's already much easier to maintain and modify imo. Ty for the suggestion this will make it much easier going forward. I am going to close this issue. 

EDIT: The update is pushed to Master. The `dist` folder now contains the compiled Blunt.css file and the SCSS code is in the `src` folder.

**Comment by loup-brun** [comment]
Very nice! Thanks @f-prime! 🙌

**Comment by dlewand691** [comment]
Wonderful! Thanks @f-prime
